// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Client")>]
[<assembly: AssemblyProductAttribute("HelloWorld sample")>]
[<assembly: AssemblyDescriptionAttribute("HelloWorld sample")>]
[<assembly: AssemblyVersionAttribute("0.1.8")>]
[<assembly: AssemblyFileVersionAttribute("0.1.8")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Client"
    let [<Literal>] AssemblyProduct = "HelloWorld sample"
    let [<Literal>] AssemblyDescription = "HelloWorld sample"
    let [<Literal>] AssemblyVersion = "0.1.8"
    let [<Literal>] AssemblyFileVersion = "0.1.8"
    let [<Literal>] AssemblyConfiguration = "Release"
